name: Tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build tag push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: cgnetwork/trailarr:${{ env.RELEASE_VERSION }}

      - name: Build tag latest push
        id: docker_build_latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: cgnetwork/trailarr:latest
